services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend: